---
- name: Check 'item.name' parameter
  assert:
    that:
      - "item.name is defined"
      - "item.name | length > 0"
    fail_msg: "parameter 'item.name' is missing"

- name: Check 'item.stream_port' parameter
  assert:
    that:
      - "item.stream_port is defined"
      - "item.stream_port | int > 0"
      - "item.stream_port | int < 65535"
    fail_msg: "parameter 'item.stream_port' is missing or invalid"
