---
- name: Create config volume
  file:
    path: "{{ motion_config_volume }}"
    state: directory
    mode: 0750

- name: Create log volume
  file:
    path: "{{ motion_log_volume }}"
    state: directory
    mode: 0750

- name: Create data volume
  file:
    path: "{{ motion_data_volume }}"
    state: directory
    mode: 0750
