---
- name: Check role parameters
  include: check-parameters.yml

- name: Create volumes
  include: create-volumes.yml

- name: Create docker image
  include: create-docker-image.yml

- name: Template systemd service unit file
  template:
    src: templates/motion.service.j2
    dest: /etc/systemd/system/motion.service
    mode: 0644
  notify: Restart motion service

- name: Template motion config
  template:
    src: templates/motion.conf.j2
    dest: "{{ motion_config_volume }}/motion.conf"
  notify: Restart motion service

- name: Template camera config
  template:
    src: templates/camera.conf.j2
    dest: "{{ motion_config_volume }}/conf.d/{{ item.name }}.conf"
  loop: "{{ motion_cameras }}"
  notify: Restart motion service

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Start motion service (if not started)
  systemd:
    name: motion
    state: started
    enabled: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
