---
- name: Check role parameters
  include: check-parameters.yml

- name: Create volumes
  include: create-volumes.yml

- name: Create docker working directory
  file:
    path: "{{ motion_docker_working_directory }}"
    state: directory
    mode: 0755

- name: Template Dockerfile
  template:
    src: templates/Dockerfile.j2
    dest: "{{ motion_docker_working_directory }}/Dockerfile"
    mode: 0644
  register: dockerfile

- name: Build docker image
  docker_image:
    build:
      path: "{{ motion_docker_working_directory }}"
      pull: false
    name: local/motion
    tag: latest
    source: build
    state: present
    force_source: "{{
      dockerfile.changed
      or motion_force_docker_rebuild | bool
      }}"

- name: Template systemd service unit file
  template:
    src: templates/motion.service.j2
    dest: /etc/systemd/system/motion.service
    mode: 0644

- name: Template motion config
  template:
    src: templates/motion.conf.j2
    dest: "{{ motion_config_volume }}/motion.conf"

- name: Template camera config
  template:
    src: templates/camera.conf.j2
    dest: "{{ motion_config_volume }}/conf.d/{{ item.name }}.conf"
  loop: "{{ motion_cameras }}"
