---
- name: Verify
  hosts: all

  tasks:
    - name: Should template Dockerfile
      stat:
        path: /opt/motion/docker/Dockerfile
      register: docker_file
      failed_when: not docker_file.stat.exists
