---
- name: Verify
  hosts: all

  tasks:
    - name: Should template Dockerfile
      stat:
        path: /opt/motion/docker/Dockerfile
      register: docker_file
      failed_when: not docker_file.stat.exists

    - name: Should create docker image
      docker_image:
        name: local/motion:latest
        source: local
        state: present

    - name: Should template systemd unit file
      stat:
        path: /etc/systemd/system/motion.service
      register: systemd_unit_file
      failed_when: not systemd_unit_file.stat.exists
